### ISSUE TITLE
[BUG] Module Management text unreadable

### ISSUE THREAD

**Issue by simtudor** [Siggysaw/arcane-arcade-fallout#29]
What you are doing, importing this system into Foundry, is amazing. I was going to start testing some Modules that would work well with this system and noticed the menu I very hard to read.
![Screenshot 2024-05-21 113331](https://github.com/Siggysaw/arcane-arcade-fallout/assets/4055239/0e4388bf-79ce-46eb-9f59-31e9c5102fcc)

**Comment by Siggysaw** [comment]
![Screenshot 2024-05-21 192018](https://github.com/Siggysaw/arcane-arcade-fallout/assets/168799854/5eb4c4f9-aabf-4817-a31a-eea8fb36746b)

**Comment by simtudor** [comment]
looks great
