### ISSUE TITLE
Ammo cannot be assigned to weapons

### ISSUE THREAD

**Issue by chrisjbrown** [Siggysaw/arcane-arcade-fallout#40]
current experience
When equipping a weapon on a character
There is no option to assign an ammo to that weapon 

expected experience
When equipping a weapon on a character
There should be an option to assign an ammo type eg: 10mm, 10mm hollow point, etc.

**Comment by chrisjbrown** [comment]
This was previously working to some extent

**Comment by Siggysaw** [comment]
Reworked the Ammo system. Now works with special ammos as well
