### ISSUE TITLE
equipped armor container is shown even if no armor exists

### ISSUE THREAD

**Issue by chrisjbrown** [Siggysaw/arcane-arcade-fallout#43]
equipped armor container is shown even if no armor exists
<img width="1339" alt="Screenshot 2024-06-23 at 10 30 57" src="https://github.com/Siggysaw/arcane-arcade-fallout/assets/1250638/54900d2e-d256-495c-a8e0-7c7a45fd2cf4">

**Comment by Siggysaw** [comment]
Added headers to better differentiate the various slots. Feels less empty now
