### ISSUE TITLE
Error message when equipping armor and deleting equipped armor

### ISSUE THREAD

**Issue by chrisjbrown** [Siggysaw/arcane-arcade-fallout#52]
![Screenshot 2024-06-25 at 11 36 57](https://github.com/Siggysaw/arcane-arcade-fallout/assets/1250638/9e951840-682a-4002-b594-1d1491beea93)

![Screenshot 2024-06-25 at 11 37 43](https://github.com/Siggysaw/arcane-arcade-fallout/assets/1250638/5fbd9039-2085-4efc-84b6-8d31b60efae1)

**Comment by Siggysaw** [comment]
Error is no longer populating as described
